### ISSUE TITLE
Unable to resolve class Language 

### ISSUE THREAD

**Issue by Bartosz-Kozajda** [grandcentrix/PhraseAppGradlePlugin#1]
I'm trying to use the plugin, but the Language class is not found. 

And probably you have a typo in a readme:
`appply plugin`

**Comment by StefMa** [comment]
I just fixed the README https://github.com/grandcentrix/PhraseAppGradlePlugin/commit/0efc1b6bcf68bfe2073ebae6df69bc50e5035364
Thank you 👌 

Do you have error output or something for me?
The `Language` class is inside the `net.grandcentrix.phraseapp` package as you can see here
https://github.com/grandcentrix/PhraseAppGradlePlugin/blob/0efc1b6bcf68bfe2073ebae6df69bc50e5035364/src/main/kotlin/net/grandcentrix/phraseapp/PhraseAppPlugin.kt#L36

And this should be in your classpath if setup everything correctly...

**Comment by Bartosz-Kozajda** [comment]
now the issue is `Cannot create a proxy class for abstract class 'PhraseAppExtension'.`

**Comment by StefMa** [comment]
Which gradle version are you using?

**Comment by Bartosz-Kozajda** [comment]
4.10.1

**Comment by StefMa** [comment]
Please upgrade to a newer version.
We are using some newer APIs from Gradle which are not available in 4.10.1

Am Fr., 17. Mai 2019 um 10:48 Uhr schrieb Bartosz Kozajda <
notifications@github.com>:

**Comment by Syex** [comment]
@StefMa Then let's put the min Gradle version in the README

**Comment by Bartosz-Kozajda** [comment]
Unfortunately I cannot upgrade the gradle yet.

Can you add some min. requirements to the readme?

**Comment by Bartosz-Kozajda** [comment]
Updated the gradle version to 5.5, still unable to resolve class Language
